### ISSUE TITLE
Enable communication with Alphasmart 3000

### ISSUE THREAD

**Issue by isotherm** [lykahb/neotools#4]
I tried lowering `PROTOCOL_VERSION` to 0x0220, and neotools seems to work properly with the AS3000. I tried:

* neotools mode
* neotools mode --keyboard
* neotools mode --comms
* neotools applets list
* neotools files list
* neotools files write ...
* neotools applets install AlphaWordPlus.OS3KApp
* neotools applets get-settings 40960 # 0xA000, AlphaWord Plus
* neotools info

I could just open a PR for the change, but I'm not sure what the differences between protocol versions 0x0220 and 0x0230 are, so I am opening this issue for discussion. If needed, I can do packet captures of the AlphaSmart Manager 2.0 communications, or verify certain functions that could be expected to have a change or problem.

**Comment by lykahb** [comment]
I believe that the difference between the versions only matters when updating ROM. For the details, usually I look up the logic at https://github.com/tSoniq/alphasync/ as a reference implementation.

Testing the changes is good enough, a PR would be welcome. Thanks!

**Comment by lykahb** [comment]
Released a new version.
